version: '3.8'

services:
  # web:
  #   build: 
  #     context: ./mysite
  #     dockerfile: Dockerfile.prod
  #   command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.prod
  #   depends_on:
  #     - db
  #     - my_redis

  test:
    build:
      context: ./mysite
      dockerfile: Dockerfile.test
    command: python manage.py test
    volumes:
      - ./mysite/:/usr/src/mysite/
    env_file:
      - ./.env.test
    depends_on:
      - db
      - my_redis

  lint:
    build: 
      context: ./mysite
    command: flake8 --ignore=E501,F401
    volumes:
      - ./mysite/:/usr/src/mysite/

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  celery:
    build: ./mysite
    command: celery -A mysite worker -l info
    volumes:
      - ./mysite/:/usr/src/mysite/
    env_file:
      - ./.env.test
    depends_on:
      - db
      - my_redis
  
  my_redis:
    image: "redis:alpine"

volumes:
  postgres_data: