version: '3.8'

services:
  web:
    build: ./mysite
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite/:/usr/src/mysite/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - my_redis
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  
  celery:
    build: ./mysite
    command: celery -A mysite worker -l info
    volumes:
      - ./mysite/:/usr/src/mysite/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - my_redis
  
  my_redis:
    image: "redis:alpine"

volumes:
  postgres_data: