version: '3.8'

services:
  web:
    build: ./mysite
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./mysite/:/usr/src/mysite/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: