###########
# BUILDER #
###########

# pull official base image
FROM python:3.11.4-slim-buster as builder

# set work directory
WORKDIR /usr/src/mysite

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

# install python dependencies
COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/mysite/wheels -r requirements.txt

#########
# FINAL #
#########

# pull official base image
FROM python:3.11.4-slim-buster

# create directory for the app user
RUN mkdir -p /home/mysite

# create the app user
RUN addgroup --system mysite && adduser --system --group mysite

# create the appropriate directories
ENV HOME=/home/mysite
ENV APP_HOME=/home/mysite/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends netcat
COPY --from=builder /usr/src/mysite/wheels /wheels
COPY --from=builder /usr/src/mysite/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache /wheels/*

# copy entrypoint.test.sh
COPY ./entrypoint.test.sh .
RUN sed -i 's/\r$//g'  $APP_HOME/entrypoint.test.sh
RUN chmod +x  $APP_HOME/entrypoint.test.sh

# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R mysite:mysite $APP_HOME

# change to the app user
USER mysite

# run entrypoint.test.sh
ENTRYPOINT ["/home/mysite/web/entrypoint.test.sh"]
